FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

RUN pip install pandas 
RUN pip install scikit-learn 
RUN pip install tqdm 
RUN pip install scipy 
RUN pip install matplotlib 
RUN pip install seaborn 
RUN pip install einops 
RUN pip install tensorboard 
RUN pip install numba 
RUN pip install pyprojroot